name 'puppet-postfix'
version '0.1.0'

author 'Proteon'
license 'Apache License, Version 2.0'
project_page 'https://github.com/Proteon/puppet-postfix'
source 'git://github.com/Proteon/puppet-postfix.git'
summary 'Puppet module for postfix'
description 'Puppet module for postfix'
dependency 'ripienaar/concat', '>=0.2.0'
